#!/bin/bash

if [ -n "${1:-}" ]; then
    day=$1
else
    read -p "day? " day
fi

dir="day-$day"

[ -d "$dir" ] || mkdir "$dir"

for solv in "$dir"/solv-{1,2}.py; do
    [ -f "$solv" ] && continue
    cat > $solv <<PY
#!/usr/bin/env python3

input = "input"

with open(input, "r") as f:
    pass
PY
    chmod +x "$solv"
done

echo "Input?"
cat > "$dir/input"

