#!/bin/bash

if [ -n "${1:-}" ]; then
    day=$1
else
    read -p "day? " day
fi

dir="day-$day"

[ -d "$dir" ] || mkdir "$dir"

for solv in "$dir"/solv-{1,2}.py; do
    [ -f "$solv" ] && continue
    cat > $solv <<PY
#!/usr/bin/env python3

INPUT = "test-input"
# INPUT = "test-input-2"
# INPUT = "input"

with open(INPUT, "r") as f:
    pass
PY
    chmod +x "$solv"
done

echo "Input?"
cat > "$dir/input"

echo "Test input?"
cat > "$dir/test-input"

echo "Test input 2?"
while read line; do
    echo $line >> "$dir/test-input-2"
done
